# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

activation_function <- function(activation, input, decay = 0.1, floor = -1., ceiling = 1.) {
    .Call(`_PCSinR_activation_function`, activation, input, decay, floor, ceiling)
}

update_activation <- function(activation, weights, decay = 0.1, floor = -1., ceiling = 1.) {
    .Call(`_PCSinR_update_activation`, activation, weights, decay, floor, ceiling)
}

check_convergence <- function(energy, iter, stability = 10^-6, convergence = "floor") {
    .Call(`_PCSinR_check_convergence`, energy, iter, stability, convergence)
}

convergence_floor <- function(energy, iter, stability = 10^-6) {
    .Call(`_PCSinR_convergence_floor`, energy, iter, stability)
}

pcs_matrix_cpp <- function(weights, start, reset, decay = .1, maxiter = 1000L, stability = 10^-6, convergence = "floor", full = FALSE) {
    .Call(`_PCSinR_pcs_matrix_cpp`, weights, start, reset, decay, maxiter, stability, convergence, full)
}

